apiVersion: apps/v1
kind: Deployment
metadata:
  name: mighty-quinn-www
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mighty-quinn-www
  template:
    metadata:
      labels:
        app: mighty-quinn-www
    spec:
      containers:
      - image: justinquinn21/nix-foundation:latest
        name: mighty-quinn-www
        ports:
        - containerPort: 8080
